---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: lldap-secrets
  namespace: auth
spec:
  encryptedData:
    base-dn: AgBK9xpRAV8aP0+IQVhU85j4rmSlfTwzSzFvz0RnI3l3FwNVBO5MOlH49yMaTqtmkd1A88U+hilee7fF4UUAzOvJuPEhXvm5FA/SKj6d692zlg9A/3zFnnYG1BRyHDQklxwn0wEmItrzuO7JRCoIUjI2FiZm1zzzzGG5mEF74enKWcKIxaApyKNnk2Xxyb2WVNDQeuoTMT9zJM00nC2cqDcSrtW4uvWfHK+Yx3q7ulfg0IsN2jFdTLiR53Oxq2AbcgFR/JTvnoN1kOYVHZxvL53qtQKw83J7+AclKHebo6R0i4sVobSbVvajorGruE80BqhlTQErWreDTKsLB9xHVI34Xb7D419fTB4O13jZfNQkMCjjVvw0Ktga/5pgBqvN9ryU8aafgzTfP5rZ3xWXkRxKJRMNLkQqdHSKeaBKzyqx+6nOKFpoK8TQ9u7NMcKCCVS2Y6IXQVcZRIkL5gF50RB5g/NGb5VBltWJKMFLW5amLnqAyff2+JoCitIueB2QNfkkoDUykWshjU43Yrbp0Eizo+Cgf5QdpffNdiqRGLhyYchoWeG0dubBL7ahzYwWDtgqDBRqtKNDD0O+Lf3eixNvX+j+lIyPT6EtkWHYsgiQDab4M/NPaA+gjzINCubf61ajdXufpG111F4byUx/cGIY0weUwe6cAZotsd0FQtF2VqEIHWHvOVHkTKcW2tbVYlWoMGOHH2MfimD9ZSFOkg==
    jwt-secret: AgAdNuaIFAi0VH4i1yORD8E8OCQiiTtw87AFOQGLPSVPTxON9jDWEHpv6vGTlmjBIQCe+tBXmjPcWEeRldswdrMtTA/ZqoyPBJqKsbm6umqvkUfcxvVTZghBqzEPFNBFiWhU7ETburC9oyqU/9lmtjXBE6RSEpz3e7WqAfpto3DsKp5k0KqS/hoClMsiYQHH1D8Lua/ZzLfQ4Lz3dHXSauNad6cLgyMZM3fLYGSINZrTXNQd0dBjVkqYXkrtDwlmhvbIYoqxm5iXJmbxu+Z8rssl3iL28HBDXdckAhkeJJLFZR7xwkUSoNhztZRtNEuoxW2NW9fu+h2CLR4sT0GOEP/l03SEzJXccow1iTF5O6zRxgYKa/d2DtK3tGN3Frol/8U7NMkI/N+LoeTO3XBFcVjBOZWOqOkBjFNhlHLpPhV+H72Kw4yrV+RQLPei+PRbFv7mgS7tWDK1LCBr8dndSozbFMa2IOnlCrlcYW/TmrfzvC3NhNBzSfmS3F5+DmwMU1cvWDB9CEqSt8GwxVwBoVTloenrTjQsa0Bu5MIpvU3nkTmzshfxf3+5lGR2C2e1c2O046BEZoYh3mxWGVB1c5Spyq1SnrWBcmN8ECDcjAev9GqstHbBriWl6Ifk4jurYYx6ILkdp7PRT2uBfko2qNFPdnp0vo2gIXZm0RKJ+DyryThfy56QxOiRbwyoxVrFkwnGb7tbltNMm+J7z4W42z8GaSuKHfIMvuuk6EtaiD2B+jLVB/FWX2nsi4BvGVoah5G4fqekbO/UhFdT79UMuv+x
    ldap-user-pass: AgCEtEWDaJ+2MQO+7s5DkSc3n+1vX4vVeTH9m7ZKTSm8Ia8mVUChi+/SeL8t+bUoPPZwSARYRYpq3+v8RB+/Z1bg9t0L7hBUWxDA144HyjK4WkrD5XSKsmHuTqTOEKwAKlFav84dfsSTZTmRPollo18H+GkBCkX3P/6XWtqY9skl8y1Cx6l2vrUqwFMN3T6St6BqV3yP+otzaGPG44WjteTLayYQHcbeO5P7rnar8Rhiq1UhoPsXY/N8sTNuW9MbFgWUp9A9JkkqhazbJaxx9mM4h0Be2YuVkl7t6oznL7qamjPGMB1pgnGZ+6u/4WF34h0lkcn04QCN4BI38I1GyKadv9/VnVWJ1BfbtN3su94Axr8v248FVAqCf06qgdZEKFqZNuGiUjkW6u3NyFy9oJH7rUgVx88v/t55XO3EzOUgZYpNd6D+rILqaW3GRUKj9WwxhMxAvrGrDqPBYpul/ZkNX2YNDsGF5C/VD656dsyo0ygQxmHK7o4PcadNmqZgMpeRjnxzag/+8OglGDmXXkFTZurkA7fpgr0XS9rhP5qJgqoFd+0Qrksoa/ng1F5YN9ClR5rwUas7LW/bsz0+XvMjTo+HRsdtAfhcWqude3bGZt7imwtfnrJjvFA4ES4Ngr3u0F6qAONaG1MPgCpprNwmD00dXm9Y3jCJmJgiyjUlMBopk0dtijobnG17qNiVSHDL/Rmti/Oxh32K2NXzc1wu+jzC+fVh/cAORyD4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: lldap-secrets
      namespace: auth
    type: Opaque
