apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  namespace: auth
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
