apiVersion: batch/v1
kind: Job
metadata:
  name: lldap-bootstrap
  namespace: auth
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: bootstrap
        image: nitnelave/lldap:2025-04-25-alpine
        command: ["/app/bootstrap.sh"]
        env:
        - name: LLDAP_URL
          value: "http://lldap-service:17170"
        - name: LLDAP_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: lldap-admin-username
        - name: LLDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: lldap-admin-password
        - name: DO_CLEANUP
          value: "true"
        volumeMounts:
        - name: user-configs
          mountPath: /bootstrap/user-configs
          readOnly: true
#        - name: group-configs
#          mountPath: /bootstrap/group-configs
#          readOnly: true
        - name: data
          mountPath: /data
      volumes:
      - name: user-configs
        projected:
          sources:
          - secret:
              name: auth-secrets
              items:
              - key: keycloak-user-config.json
                path: keycloak-user-config.json
              - key: user-1-config.json
                path: user-1-config.json
#      - name: group-configs
#        projected:
#          sources:
#          - secret:
#              name: lldap-secrets
#              items:
#              - key: admin-group-config.json
#                path: admin-group-config.json
      - name: data
        persistentVolumeClaim:
          claimName: lldap-data
