---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: authentik-secrets
  namespace: auth
spec:
  encryptedData:
    authentik-postgres-password: AgB6QDyTOmwH+Nn+F/kdXqJj7PHaEky10JbpyslBeBqssyck3IydPoauyxGP559AjObO9JFW6m507RyVUTh6i5xkWEVeuVajamcSoTVrJCpLb8+uhMRnp0se/zr3cqJ5EUAJSHDWEMlm4K8YHNU5oQswzqxOdPb9nggqvzICnEhNIeDAezQwSPjXE7RFupypgDb2Yus/6VrLcrJ+KoDOqDTuu5M4nJuB/nq6o4XXn0/YIOyHW4zOTPoFo9ghBbWRxpCyT98EAxJfsTZGIeN6KJg3yusgi+sDdCgFs+0Q2wkoysFT2gyxMiY2mQWN6kJTvFDaivQePaceqETj0llqIZEJfh8l5lOzGVUxY1T6K8oiAGBCeiV7FeLEFgq7PzLr45VieUcebt86peahltOIazMLiNChe8GgtbdS2zpBeGUQj9WfdUib4G4YZnBggWqlBsNs+X6VHEGk14Kn59L0HJx78sDwJuXs4inUisdIqgxSgJS0JlWG8ch2jGtp4uInDwL42dBXlR78/R/4i25YBIZt35zBQPB5umYEiPAYKwBCSi2P3mEgsp93lzSARn3XqdNM0VjEBU1HwVMlwwvXPWQL5mAw9I6raW4VZemy/9ymmISf73Yih67FTG8F/wkR4QQdJgCyf+87M/NMt45iTIEsGQVJNvcG5eqgk5bMyL7aE3PvCBU+OfoRRQ5csIoGWm8EDsPoDg==
    authentik-postgres-username: AgBU3lUWgduIU0eAZy0R6Tvf+/V+dvj+wSwoxBTwznQwzA9LT0JrhQOyXKUWxuEAiLPJJmg/E7xwHcQ/UZZeFVaOYjxbVqWpkMTWfEIyQeO7Ozce5UgHEbRJOXgY9CR3s/BX9Q+YGehMnnnJ3tV58US8BPCH1EZbZok4ljF+ANiHIBClCShpZN7DIczXR3lKswsmChq3AC86tR5NSihOwMxbrnvtvXkZdrkAeuIpVitpCh6XfYY62OgvDIXsnvy/mQZaPkZJP/mKYBQs8n0+cFNw9uLlLJTH4WGhovPtJnuqts0dSGftUytxC+vk/7QFvMVAxpQUkDB0JJKze6V5P76zw0nwtuikC2qzZpL0stGuvCO/R2boMCStD0V9xtOQMaAXbBimkFUG41dDhEgj68JLI8Sv1k2jF64TphCBYtdAeLJDEPeVD43pmf0ZVe0xwcjBrHNyoYLvh9erDdQpGKFb2Na8zle843EQFnUs1kAzxZnVEw7m2RWQGbWd4LqQWswM3u4V23VCQE6pTJy5hyOdWKulWZkyzbdSZpYwp9IVk/JjQhQgXCyl7Y/ED7RZU+Ig/TQHeHfrKfYkhdaWTUrDXn7mETLXamA9K3pfh+3U8lg8kNABYrSKgQBZXMsVvYeF7O+2mFHwlpJbNUoiz9jCkM8em/hulCGb7KvJqpLXkvPyITrzQZJlgMcFjTTqHhhiFhBrfA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: authentik-secrets
      namespace: auth
    type: Opaque
