---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: postgresql-secrets
  namespace: auth
spec:
  encryptedData:
    password: AgCDG2P60tRSZm+pZ5uIiKO69YInT+HSMc1WEZ91aF06caCu8uEu/YJY37fcyBO++Pc+tWepVng3SGIJ2Hlj4DH65Ho6wP0SEHJkSZcGjlYQ4F5FGh8+rne8s92U5PZNJ+DIQCj2Q+kL49mHQHbylrMrBS/VkjigZY9lcyL+tUNOGV7KfAbqonwkVypugI63OO2HZTMIMwzNPt14GTxoSqxb6hwraxpr7IcjNoUyhVixErl/u1qMexjyaI9UbRtU7bg/ApaLKDVd7KvRTav6AKyZYPLf5f+Cy4qFS5NI70ldtEErmgo/wjW82sTSQK3UrTa50ceHFpBP3LqkFNldzFg40FVVnYrRX/gvWBhsCHbZDBXrhaYcGfHnijWQZLSw9f1C4qaC3++vghq9/bXF4PoCn38nW2OCNIzpKcZGlKQD+16GB615dEMy6CggN5SF9gPiINJ+ku3loRXNeJf4tExdB9pZjS27BSZekSXkVaol25R5bTkJN0c4/sgKRFOS7z+lmvgsIr7A/aK9IMoCWHU/3ZXxDUo5+fkqIJY4ZjF9ivj0AN7ZRWz0Uon3m5EPlUKwlQW3RZHysVdWaYOU95Xq6gJMSkRekIQ7EgZXLVXJXyeKP5ZodbuugpiJvyVNj6GNkBJLaqQuuWPx0iJT2CEJwInFBUIce8yLAaUJtooE38a5lieREUfDdd/4y23iaMHnFgpP6A==
    username: AgAsNKkJbkfbf4wDqgqs9j+e+yysDFEOMKJkQS3O/6pxwXYX61RNWPZBdw7Uy+3lpCXiT5lxNZu0WJ3h40LPFnnq0zDAhv9wq7k7ww9FMUlS7UYG1ie3lzU07o5jvCKk/QdCgjDHctf8Xrc0gdkLLe00J8XNk4Yt4I97XTXVyKdn1xVDTbsXkVeZh0i70WY+GPbAcweeGPpY2RF77JQoemLx0oIuWHg9mcE9dsyq++oUrmDe2uptHKWwslLYxkx+7Jp1xHF2q9lFbLTnzt3Y7hPj4PFmG0aYBZi6ZVXAGaaO2jnXdXqVz/ULwh1SpfhozIYaQ/tEw1/SRnR9Xp836vy4xc+hAQgLCKluEV5yDGhLPAD3e8LeSC7OnAwP6PQkVv/w8xGm4SwNek5ro3/6g7NygzybmR8l74h29sDG8UDJUSxBQbXKmAZCrBSPTUSupTdvdjeWttxGNVicrt2xTAiyBt7Q/kSxr7bEkf5YhkBtMCRHxPvPtX/mgRRR8l4qYjoo4DObjrjFHHh/YM4dCJqD9H5shlezn+ejlCaJ7k3IYHuz6bQ7nfKVJ3sXpDYEQHNBNCZ5ByuPCHk2ELvE5Rr64Ab3CxQsMDGnjvRmH/mi9nq8zHTxGd0Mq8HiYSPt+g0vHJsXtad9ZRKdLtFZtW2TTlJ6iF/oJGB85fJ1KXVNyE911MTv0z8XHcupFX7GLaDiiqG8haenBM4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgresql-secrets
      namespace: auth
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: authentik-secrets
  namespace: auth
spec:
  encryptedData:
    authentik-secret-key: AgAPu4vTPub05GAwgfp0RUjUV/gaG3bPhshUGyNuiLQkNJDPqlONMbj/aLoHRFn5S/DmOOC+WhSXvB4lmtuwAHOtu/s9J6An5HGjTU4U7wqzQ7FWG9jrt1kYWv2wKaNjOxg8Tes1PpHd5NM8UE7Ot1hKwzcGsr8ERXX/DW/AJ+DEuCjDuISIcm1aY2Z/Jb2wIlpsZujLbK3X/9kIEEkEaHv2Gg62tjyivxOpdJ+XjNtRCsZuqrDZeHk1/85cObFw85ZM6BFoGI4ShcYWoEgGEnpJKCsuT2i7bztBH3mnzKiHp1y8Pmx6AZb2mHkE8S9yse2bHdJzL7X5IOx8ihGntdxET7fPpXrX/mq1JvISvQxiH/JcSFB56Ymokn7F2py2lc05oA0x7y25bDRQ9AfPLIm+WannAq4g5g3YFa7cSW12ydZ5nE6qJswN7LRQ18jd7nRIVZP4i86xizBMPhyIo6iQNxo6wUNkB10597GHrjpoyEGZq25Ks73A1lFSXtyfL+QQQBx9sjTjXGVnuYjYksBhGnM8wDtH2Z9y6aFhHGRpdiQrCG3hFWNJI4lI7Ilo9NlITwd/phGv5D4Gzl2AFq1fUnTSSUp/NM6wxsCYeso2p0pWiRrOPB/4heh5V3QZ0gcrEoG8lV5OfDLwiigj+PcLGjscWi1+cHQhUYipJK6RcV3DaJv+1qZIye6N6CdWuDc0w9VRKC1OMLSK0e9s/3Z2c8cYWGzakB/NAVxaSlRuTbvztmP9ulFi+bCAixOK9Vu+WQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: authentik-secrets
      namespace: auth
    type: Opaque
