---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: postgresql-secrets
  namespace: auth
spec:
  encryptedData:
    password: AgB+G3wtZDZBMzRccNx+9DcYvxRmP2S1bTNHSWFZwTPlDhOdCpwMpi4R08WJjA/0BMLDgVotm8fTZDqf5csR90Lyg8sI/cSR2dKWxyv36pjfn2/SLJrO5YP5i5i+DC6uKOrROOv5YutXvjGDZqni512m04tX33J5rihOT0kNisicdtAbqpAFl/aX9b+f35K6ultpx/lIpb/ucIYDf7mBQwdxSy3anB5f9uOAzzc83+vq8cnjEpplqzaVY+YVWdqswuEwTtszBkzpSohWaNtVrFrEVPkTxdagMVm6Lbzombi7ACrG1/OvQ02GxkbVaSywhyjEi9H6N4AQbcNNM42BY3j7dhy7GOMa/4fLjYBmIy4hWozsiAa/dQZiKkjY6YKzn20cL+XqKQrSaa3z9YekZS6O5bDOCrbaMVVTtwsReBPzptCrY0V9ZuF/Limunkvpsjuhnb4xJuSZ4YGEFR5ulYiZ9PtHgz+K5FhbEzJi8YO8s3FmqUEUcI0nFmQiics3x9bm2eVLDWi4clEM3Sv1F+Shz0Jqqeerlnn5LFTFMuBupIB+xlPM1JS+iGmJyon1NmHritzh4C8Eb7HbBBqdEwc0N3y59FZgl3VsY/cepRS1tsel3NJXAoU15ZoDWc2M8hompyzFExwwwNE+JBaOGh/MA8t1rjBAdOnMzmf4CJAWwGIA4CWwiv01g4TCf702E9mvNJnwsQ==
    username: AgAR/BKKGEKv8eOkcragISXc7ZX4w9FyHsv4AZ7Y0IWHr96mW8OBhzPtHCsiAHoczHEovVmSWg4+JAHkXtLScmamTy9+Td6MK2tRTtu5MKqL7X6CqoITdLCirE+4DJYNMs7Awfzzlt5iy84iKcxAVrlGswWIHEcBNV1toTo0/sYjp9izD6XiwkulJ4mxZtPn9gtylUzkjpWZgayN/Zt8vlKe7gl/ni+rue8tqPKD/L/WSRR4W9jkVGStE4SycHwbPMYDuaNURw/ZCcumIjBCgLGQOS8QGTrMv0uW7gR2PnQSGvGrDGXKIPuRkXo2SbI0/HhaeRJb/ecK2vaYRU4JLrasQJDGOnOFMdtZXQ6soeer7HfkD1VdxVuOLAC3gjpo+fk5e4kZNw6tLMqGDKZczTquYykboTYXLkRpftQr6p/QiBA7bzoJs8fHbvF2hliYLovc4UKigZU5+6cei9kizMxYDC96cHiLJ+2XfqhfoI0r9LUIBBo3h01AqVNjxi+40JunZuweE4QNaiJvfadf+z6bkWNcaDvERhq6woszO1DNduZtZvJpcnDJmmXWfxpgcoFwvIkL3vo2xcQnyb59zjWLSKnZOxYism9ZYOA+j8tiqz71kLzITVTImHZS8BFjbGP6n+aXzGHyhJK6tBq6mfaz0mKMxHatGA9TzqLMRQ+1UQhQLK7CCh4yhnyKCHe8XUb46JHjF9qd+OE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgresql-secrets
      namespace: auth
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: authentik-secrets
  namespace: auth
spec:
  encryptedData:
    authentik-secret-key: AgA5fLpooUiZZ2f3lxlchnfiaRoA9yUqQHn3tIlwIltfXDk9sLx0QIM8YP4hc38S/mRoNckRpXkUqE42a0jXpRCehZqm18gKIAwuzLz64Q+DIJUxGLUwtoIPbdpdse/8d00mPXKX6fIaGK+Yxf32JXYJGQwHZM3bBm3ARWATGAnX+a9+4f78F4Vt6fZ5fkeGtXPrqu51gabrYyG/zfFWTSdvd+o/ddoVXr9mhaRuUqzbcvsdWNR8Sq56IeIrlCfsd+6Iwtw6YWigonqy6jCv3yFnCwjM6m+t4XE2bmayMgPMiYtOVb2ULQPqrmvY1AG1u8mEuM2vVAdft92hOFOzrk+ewZvwM6bA83a7Ag2LwG+gO1cUwrZDQLAiDcx+YIbe/HYZ+x/tbigFyaQO2puLOc525paIqQNXZtshs+ATrWZuqDVMcqir42nCJYdtUjgIMkv6EsLFb4FOxAs6H+lAkC84tvH8KA7oHK2d48hJpMufZcEw8TNVJtLChIqtXULI6fJDwic6IaIWkueU/bmRDXjRCtGEfFAX0wjWcJbs0ZFiGUqDwugA/uWwjPPgyQ5f/hXBUf4qnb32YPgw+fkR6Q7HzDq86/HfalGWQbBvsvmYfld/voiCZSmSQqiVNVZlHyQmyc7O8lo5uIpF40ki0RMMaX8Nzw6u/vP+kjLxyH+hpEwvKdH/gu7zWCNAE+SBe6P4mqev2IL6hy65FMkjnfXJ6yCFgFjQnwiHQuPm9GwMxUG84w0X75AhHLLmsETXYchhMw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: authentik-secrets
      namespace: auth
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: authentik-bootstrap-secrets
  namespace: auth
spec:
  encryptedData:
    AUTHENTIK_BOOTSTRAP_EMAIL: AgAIGBZstHieeZrhPmIARNC2ONE37urd1+K1IuLfWYHoLKcsITEN6GbruUFKS4Et7iA0rJy2TdsXPUGNGxY9nyGToJKsg7NOj8sZCPQrtlZbHj1M7lUq0qKQ1+uXloju1xc+DEA9j7lMscVNlbCLJuEyeYl2CkkuT+kKkeKSEvQLXGEDjCfi1G4895PhiWooU9fwQsQOGFEeZwc0Mz5cVXOVcLEtsadblhmOsLWg1n4FwLL1w/RwcfnE//gk7GkiHJZjMmqX+UW31+hpRjJk3dKdMv93wu0g2DH4K15cdKSUDENhyN9uELP9ccEWtDdbPaNQzHSxmsVUvdQR5ZTUQyqMxxSEg82R2JI6jlkJCt02rMbS9LVYsfGbsL3+jgnqVEz/RkC2fxPS/Xu8gyZC4KTi/Ap4DrnaSUjcuqFP0m7l1zg6oWT+8WhrKZa0qSf3qk46MsIqME+elceROXDe65BnUG5hiRaqOnsl7OHlEGzHCV7aH1E+NrWnFl77pBqKv3HI3/H94zp7ij6I5/3Ik8ESf23WacyK60DVLB56ClrXtkHcxR5DmkYuMcBrzRHZhbk3MtgH9L7if+c8XZwRHsg0r1j3aVCYOn7ovHvAwX0wnwPAu5mCOY8LSOby5uU1SrpZlHWRumvGA8A2CTccaOrnbIJfcT+9xiE+I9bn9z/aS4sX+3qYVVkyVjvMC1Q8OuuicZdXgTGLzal6b8AiHPzy7w==
    AUTHENTIK_BOOTSTRAP_PASSWORD: AgAMIAJiaLKraBQWzRA/gs/sutzH+2eOxAGe+sFAVexjJMQLa2lDCXhg9PjvyGIf4eXFvXhekOboAUxY/4wA9Q0cAKUOuCgpzfKxfIQ/RtqaS/VwaHg4KmWRTorQyfHDKUBqOi5+utFGdNQO1TMWjYYeRH0f6DoMTjiwJmg2bk6Gi6QrGsEfvayCYJV+ajsIhBEOSj1liDlyAgwF2Baq82OqRAVWX9AznWFSdtjz9652DMYs4z+TQxKPAobHIzKSULjGtltb/ZX+gGsBs2OWtvfKJikAw2Q2JxJ7o+/5qcBnjMYthztDTJ46xvOwcZsMkZMukduaSPGp741pStE3IburIa+WC8KEK03hYZt1eotvzPphi2UXw9L0JbBTEdll9y3NKlZgDbjDD5hc9/yuH8g0IPERK7SENwKkWeKeAkQQja0LkUgjrGhznwDKc9DlAUy0QjWrbPxcljBqqPNNiaOeGCVUAvbYzJ9qYocMdH4RvsKb0Yrdq7aWx/+Z7hvstyOjviitpbB/8fvFJhA5axIlvmDQITOYv9BuNiicUCbYDgsOLbBiaNg8o560nJr3geUlpjnVLk0Nxov5YxKTqV1iIywM1UpkdpowsIfAPykQ6BKPv/x+hHH0a6Sb6Ax9o45j8mOsRBsbWMstY7np5oYKBNTinmylaoAmcNil7mrmiqyhfxoacy/dEZxH1ZdfktAdIwDTiw==
    AUTHENTIK_BOOTSTRAP_TOKEN: AgB7XuQUQ12LSpQotQvlwP9UhggtYZe+dfkQowj0THhmeX5S97cR1GXq8gaEstDrCFw6EEC9OxYNaaY57cAC30jey9KhwFeypYA40BWOQ0lPTFaceMfg40Ulb2UXpHf25feIREz6Q5p0DILTSMIv4Xi3H4Hwd+iz+Sxx/u6yDOctCl+6JserwfSgloNonXXV2c0yw+PwYnuYlK9hug9292YPhcYzDL3TOZY8wZjFk/pIm2LD9JIZmPbU/TlLt+evpWUzE95D7189Jn1WcVY9WXjzd7RIyRhRlJe7MmQ4MTKAR4I5kFSSW6ZgDV3ALq9Wm1MO55vLzzw88dLFiOBcmhRwDlZhqXCe2grQDC2y4gPrQ+wKgSp9aHTmNar3h+6A0fugkmoHjKkp+w/tLhF5tGmrA27liDk+ZCgLhInjtog6Wzp19xknfR6H6DhxEU4AMaPDy4LAKOjxz4TCNsdJ6ZMjQsFQxfSDkxYROE0mX7/CfrHLYnplUJT4N1mLATNm+4rY5sXQ0QDFFxZ9nbnikuvr/9T/fC7unJNeCQ9R7sZeTyzNSR6Q/kKszqgGuDalIKRUfQbsFtUXGGsrRKPf78q/Qo59lDeiaMcCXqy3CLPn9ZpA2KrU7HONxToKiBwumBfhXrjZn5ovFJgwN5N/ftjdUfyHl5ZwIjkx/B1UnbawSp9xiB53Ujcx5a9weepkPeR5+QbAxcoKEnN+Duump+OTp4rXzJ8VUH3HOeY9VNQJTqnSf5qsMDbeahntYblN4uj5gg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: authentik-bootstrap-secrets
      namespace: auth
    type: Opaque
