---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: authentik-secrets
  namespace: auth
spec:
  encryptedData:
    authentik-postgres-password: AgBBEOHtErw7ctvN2iQLufD23mGFO+Cheeyke4y6x9hl+IIOVGPXJ08HD7dL4VsMGLCWekrSuvGtvhiBWzFCFhuXQRNGyMvcSekPUyd7TDRJnJhc97zmFWvvh6M0jtoQbvDha0lhMa1GNQEE3RnqG477nP6///72RDjkX5s38v8c8o+s4xOuE9coKSX9y+0UEnfTpgAPxEnwmh3bdPvdnbrpzIzsQ17/YmHCotVXns49hQ1ywHKHCqGm0xFtbAjq31r2JxGZll4Q+XYCklRsoLX0aZp5m3LLAy3I684hfKchI1zJHjeJR3DoKcsazM6PutNzdidLZgW1AiEL2c1Qsb2PLFKd/ed7VoRAVZwmoEBDZHS1eT9WRRSZg5pOAmVADMMWNEWgRCCMKrZ1FKjwMnKteGrdT2cSha85RoJaT2kKyERobQCbPLSZpvvOvTS4gpvYTmRaxvNIZWPytXp8srHLueCgkcPZSuAxcHdbgggXWneDRZF85xHVsfsu0/vmgts7O7rjIrywy1QhpOWpbdiuCSa1psbD8DaVhA6tjGatPZFGvTfuw7negGxi9fsK0ZfK38xQaxd3qO5hz5xcih/acgiTXd+fAPpMQ+vgenIYTHQ4TlMWL8R/0wHqHfNMPwauBDcj4vork+4j4zjhdYVBeAjRsAnRRj4DxMIl86ARLJnCzZR7abTKfQJa9ug+eIeRhgtEIQ==
    authentik-postgres-username: AgBJk7qlnquQiH1bpi4hUm7r0Gk386RRYrsHBe/c+ierFvkk4YjrePFtpQLONIS1pLy4+ZiB5Fzrclo5m6e3+P2vNwFv2ejTusQp7K5DhXll8BNvZW/N+e5zZVv3vb4PT/O10t5oTxSTOAfyhGgxoLrmq2D7QA5VzK+W2UqrPLDdED3Jp7lDLIZgOjEVyAdoojUQxBOEBlTV07c91Z4tuape7QHIpvY3+sgIxpKf/VLtQZJZJhqP5dBlnImQrxMFik9dJCuIdSEMl63Ixn30+6g4/6OxmZlAdu/80fLSlswEm+usJyaidY93DKv8dK1vK8+zvsuptNkFqMzlEw0EPXw6KHycT+h/el51nTTjfAC1iPFKbTGS8TOS0IU1vDu9oEooUfrAatRrno/b8otFpTA5kT+5uZHtrWDj1Zu4cYLNhXC7bQsRYTs6zkCTlmswNj2IlMD48Perp7I88lvUJUQn0+aba4RvkJLMPnGrGg36HUngGcztcYZGehbJwL6KeOHwpSI37injs0KnZWXJiI/etvXqbWquTNBK2xk08gn1mFYrawieND3zJ0mrRt+gk7L/XHifxiZp0rk+BsrFc9rmAbMjEdmvuwmptAoC/r3ObVIEM0OCy57FkILx3QRBjh1ygxIlp8IMLEE4waCKchIiq56dy1dns+IilrlMiNbS484OU6ckPqPSFtppVyjo+SYCdK685Q==
    authentik-secret-key: AgBmSC2E4JRc6xNigZPEJ4om81kHt095JaivA2eTyRUvx5hMqTogOmyFSJIWQZ5ZnQB3N0qSnSPOx11ZpF8bE3MDMf8VagKE6RJV5jTQ7ND6NaBcuS8pKC7UaMkfcbZK/Hl7HYEUOfWMs/1W1/3zSUDU247AhinIcRBbdAKlsJiRO0U+eTqKxtlGpU/MkNwrafkcgdlYlPj6DLd1pFgZ+G42xW2Ul3O+hw1R9muZDRmQUiwe3ZDfJNdMfGZ8qsisFw5FcdgeDh01Lo5N9TXZ2pkpoT1TMtOz663nFMHE4LiB7MYxsT21nZW50K3rL0ANTkU55bqVy06qfLmh1FcSiM1JpYI+ZfbYYF2ER7Wms0tuMHwX7wOPHFKvb1CAS9osn9/syswbnrr4FzZGGO7eYpoy+UPcd310JYWmp78TTNDn23knwb769+8bt0xzQV+9WsUAaGKn5YCtNEg3Juty0hhLli8zG9/6HQ0/v0SXH1EMN323k7wKofmtzstBAKBcRY+kp1smLUNpqoQJ9Y2zMN9y8EF+K+EDiSifDfFba0gOi2vJHhlZFeY+Pz6YUaLH3N8CC6cTMiDpSJfFJny4vKuH9h5V/3fRbmeWPMACrGgG8/ShHEyEjZaZvpSfOd1GPtUEm3oOJeT5TKjmg1lMvusPV6Jfajh0F5kJKEPuMxd0n//CQFLf/QDWxsR97lS6alXKeEhzPKKeXnn/SLv+ts1J7W2c72b0JNYrba1aG2BE2vfY9KKut7R14RYr08sqe25EHw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: authentik-secrets
      namespace: auth
    type: Opaque
