---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: postgresql-secrets
  namespace: auth
spec:
  encryptedData:
    password: AgCF9jg7Y2WkNchMJshiVXi0uVasORKFbCPAjr0ebzAfzJTE+GFQgrIH001ej46yyeyv3D/+Z6NyNvpkGAEfU2RoXqeIdFjOTV05koQb5aBhcrSIrjjt266DNh7loR0rgvjh66RG8se+dNoK7LCF5cGo7ARbRg90xX93TiyWU6Ou5jgV0F6q/LpxRM1Zwz3A0Z492h5oZJOib+SjJX0PK5i6cBFC9Zd/9WbiOPz7YdFapzJt5w6aAhWWUfJAMN06YZ6JG+glJhA7EdHG5K4/mI8Z++46jUgG5Q6xHfpvao7MrTEoCOCt4YYASMJILA46gHUtKMEGwbYYsgN2e2hLQ/ZEBXqW78w8L4O5P5QIpAQbrJN/SOEIsAPjJmI5rQWbcxr55FKPf/8ZjRE4/eA0AWRXJ0lJDvcdghM6OuEvgS+axXKBbphYdQlt/cJ1S/kX1KMgBpuT11FfNWJLPu1xNhWsL/7Bpw3Ct3dfyv8ijfHhc8ABQf13/BS1Iz9/frqepuQrF1oeycwH3QiYjnXQBQ2Fq0cGKB7FN56Z9x7Hmt4H3n0+FH/PjeJU/2qTaLSi9ILdavE+Sjtf/SdiVIUDfGaT7/gX/toiZ4Hr6WAZjDCvnWWsuG1HHWrd6se+gp66gSZvZCVd2l0823NC1Z3gv1zRPZV6SOmpQZMmmcTjmse723hXU8brLpMRdWQCHQcdUMRekJ90GA==
    username: AgCSB2EVNkSUdfHtoIRsT2FHP1hZCprpvpz954p77Zt60HdwMYWj0yE6cdLLkQZvqXnWuv2I6sSC71yc5ae2ya9/kZekX6bZlEyal+M9XdbBMZnG+h4rKSHs4W3Vj+ynJMLJDoYjLVdyoA2dndciIzNhWLv0xTrvPBHXosYHcJ4AvA/MQcyaXPVE/npcOdQDZnaNx1cVjOeoyiwZ3zO2nMACGG1ADsCXHaEbkCaUGhWjDLUVMF1kp00mVh9ew4Y01oEWWwukubLMdbPUi5PwgaAVnLPfg2kSMdfAqv4h9FmEEq4C4MZfRPk0bz4V7xOETt9UQwAZeI3R774jNJK9lTVFxz3S/iyICIq5XaiDSI0bdc0btS7luYMoM1PeQ5K5VXWU2OHZiRZNtBWedurkiM55/JVFv6XeGoup2suIL/0QsEoxO/SHUMZZYh65sZ/dq05csUoE158GinEvSjSAMMs8+G4UyxX4Z9fO0YHliZSrkASFSTWDhZHog0oHXmO/CPNkfPB48RHF4IfFfeGvZE375TO3I9OxpHwnC8dXTm9XhRYzCx3A7+ORW8gDY8oEtg/qrR+/33WjxYiCfULFuobiaTFEAq0rBQwHZqaMmbJPL7iutQoka3i2arfZ4SyyRGDFnyED+FKbbB56ZOOu1t8PWN2LXBZ2MKpqqOdNv1SrxyPCelSZXPM8VPpUVkJVrDCnIIskHR3+M1s=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgresql-secrets
      namespace: auth
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: authentik-secrets
  namespace: auth
spec:
  encryptedData:
    admin-email: AgBTlECg3Px1Rhtgtuah0xf61tnQmvwmv2tPBZ+4mveYNmg6MXYQZOhuI0DMUgmyTb85R9sgsqt6fJ0lDj0TaNBE8MMPxz0cm4NbWV9iREnDNfky1OvbeRq7czvcSMeaZhmGtZVYGLD1RA881ucR5f0nBeJbiyHnHMiC2z6WJRGnNcA5zvg+gEiLOTLLZhZe5mALb6f1GeHvJk421n5tDu4fgQ+8b8SkWq2RhccVFBgkfRwPGtwcUpPye2DYF4v8v2xbFyG7xqyV62xoKUE+Wr9qUWhKlC/V1xC6dtxpukQH2fiO7bBE9VDdP18e8C/P7RrJsLvitKS/PFd3bYfIMBeh5cht55knlqV/Nr0C+6ARNQE0k9lqwt/5KUYf9FlRX+l4UHKd2th1k2ipe/B1gUOnRAxkBrqouNKcmYTbDju1EJn494lAeYrHjk/6WjDgbqaJsQIIhmbSRKOAaYTK/JJcf11V3FNilPPitm0B0YpKnXeWD+SnRyW6XxKe/321fjPferwqV9i+UfbMbbXSD57LhKsQT3WczHgi7iOuLK5fBfAmbuXQYOOKKgkFChwsoq/av7eH44qKsb+1y3/fgdbIo3rLRNQ912CBe0Aw06wYVTNZtvuGD+ojdBVx5w6PcAmbz2sExL1pQpqvB62jpuZAHx7Bcmsvr+qkWCq1IQ0g7PclbIuZ7Ut57XnatT40J2vUrKVtN980GRcpqODnKNAfTQ==
    admin-password: AgA9BHa+CJTvYmuhCLfAZpq8zmpa0ov8TbssPM+CBkEcNcozUinicSz9Q+Dy1AXyfRhUm+W1LcbYGVKCxsh2qF1HU/vuf4ygg1TnFlAdmQMpgnw/ru1Xel04F/OPpEYLN+OAFW45V/1hMpO0tXusZkm7if80D2948PKywS3mgkqUuWIkngfG4KHrH9uYbOmD/Z59oh1jy67SUuX7RlJYDULXKGM3znsLStn1AMEZp3YrSDL9ClZYEpGoIdMp354DTtEkFE1B4r3wPb68KFUsKtW1sTC5AmVPaMzIofxcMpGXI4mmqALSEy24RRLLTd1eDx6X9fethfxBfh0oK2IetzVEuWz8F+arXsxoaOcjyx7zZhla++ejarbkP49pDPdAaQQIIiCZXNh/UuKkohscsrcDnxkBvZueb+RQc9FWwFli7Y7QLFtLgZYWRUhaJ3UUTDXjSwQAUBx6elPRp26/M+mp5WRYNVQikszqbfJ3cZw0kXnIdEKxXbvCT1xB2/YQDe+7qyFBEn/+dv7uYa4ugpnGJl1XFsqObKjl3haCBYcWfUW49pyGpqzreC1m6KFQI1CGSz/g2nEGmCyLrbVdFNpa8bu01ArEnbCO2zPkasUlTTCdNsyGbo1JMIH9C4yanrb562xBnsvpjInshZG8QOEZEsckbiXSxVjaC8ME6ssKCoubv9V1aFePjekGh8mgMp8246d49A==
    authentik-secret-key: AgAQMW9rz2oRYCoZ463dYhaHdWeAWrd1CTYXLIBuxQx729335SmFNmFFqvGp31sdns/ppso/rdkOL0xVskJwjf5gsnWEBal5syYS15uEzZp6ouVpuJy7YOAw00+GtPjO6A139un87eFicX2r0U4r3fVYEUGlFO5lzKgGKkAhLmNhC0eW/y3+g1ndApZA9Bo6A+zh3uCSpb5kHxmY8UbUIDSYiOyGZTNVLTxY2Hj7NLQ3P7wppwTFxMbQaZIZdQHcvv0lZF1YAWB1jfwFFBTeaGJBLVb9sKzYpbNfiipM8ihLISdV4rPB1dTELcDVLL4uvs8kO7nEYEDPU5lHT2QtYJnsqsn3u6mmkt3BDMg6S9sR/zlTnUtSHJb7JOjISLQfCarg8yhlNJv6ngBgPXD2IGq4GiGLYz6hBzo4DmJqjz5TWMNlJ/vUGrJPF1sq/45ilrrABxHcgtdajfg9ZjHNNPmWjgE9NIVwxX4GxbFqoEKx++CGMc3gdl8gh7cp8DRkYffoaAHURoKn/zvf5uSgWut9sSakrQHCC96+6pvJ9cvulSO7Ox7a8Lk9tR7I5B4DdjU1C6Ne87N95g9PYdCBKdFgryBjGjadvJy/YV/Voon7C+zw4nnuz4YS62JMsIl+4RqIEOHrb1lboUMt08evm+F85+1VH5V1KOug20+YqoBc4DnyVjyCrzQY+iLV8gz3EYxzDUM6GC8pS8yvtLCp8gJznhrSEpacOzghw3bvd7b3T9GEIXplj0QEaE8znZe/vUKpbA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: authentik-secrets
      namespace: auth
    type: Opaque
