---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: postgresql-secrets
  namespace: auth
spec:
  encryptedData:
    password: AgBFamotLnmLhn9NV9HO2YFBAZSMajGNoCvNTwe+/9YtepKm3V8AgXDvDnZiepLXeltMlsBVVt86q0Md44MGaLEPfLmQu1HS/dDDW9KugezV0ZXYUG+Sfj219IsepS2FQpdxlbBitD5XlZ8Gj+X1uK5WYx/+k5K1DTgUGRB18sGA7KMxYWkMYfLwTnEHw3s8XGy0iodWZdjNjyfzDoPh6XfvIiXhqtfKFBB3/cPpu/jdVaE5EiBxXE9DT2iQPW64bS6ajociSEd9qPcjnhnrUjF2SjIvGa+A+hPqf8zIfxUTrjOUZ2nHzJS8a5YuJCTT/sf9EqqMTq2yqRvE/hnVGXxDB1sfFRrjfJ5I7JDYGIIbGCn8peI1Sb7/u85lW6ig6wJ87HRC+7ba49DMBa5uNowSoCewaFtxrgrB9Uj/73248Fwz8pHtMCI7dgi1lpG5OToFvs6RCKUHjSd6oWCMUvdlZSev0ib+nc2+3gq83PzQCPVZZUzKqRNj0euKUb48VRpqDhgQrUJdqpOqwX/RenIlTy8fQwMh2K89cvU6r7TY312Aq5yp9hnntfL1qIu/AuMBYmKktt2vLfdE/cHi+nVaOHzq0ASztab7xGhpofYL25V39K+fm/5GRIS4FmYdKs89ddKTPFziOi03TdFIEcGQv7MaKS+D28qGh8hk8Q6oYfriMl8/vBmFV5bSb59wE7+AH0G97A==
    username: AgByKzIhn5vzdcxkCj8vSo7bkYaE5RhrUCBt1KKRHuOvZX7P6RzsXSbqnvUr0Vem0m1WmAvnFEGl2+JXnja9PhIOrjKrUc4gAn36wvZDX9FKLkwFoO83xI+f20NH6u3wEoQke9p8VZZeDb0MHx1PLR2O6+0W3ttN4+SbsG92hCZVEWfEsXR+gjAPDRVs0YGllsvio/LlTQni44Azga55TmNopF2/5asD8j3vgDY85wNqx2VEuzTKc8K9CKXDjjZQeHVYBTTGowNlrFSHuywMYC8D8coKrYQXFQYo4+DM3H4lIMw8a2YcHgt7x5yFivsyH7ogy8AqdD2SYkuqNdnwpzisikOeUbQbIO1eKuKt1oFnhVP9J4CYcXACD8Qr+rNzx1EyYGkOwq9z4j7JUVOuBuD16HrbqFOV/4W+A4YfIhD69oP8BzaqtP2slSVOK/C+0PxQuIfymB+YKpxc32js49tvcR+PP1VJIplSY6HAgXpsC+uoI4Gfap1OuMUs4q8p0Xm3VcuVLG6iqsLbh+gRkV+MNn3bh5RAg5VhkWq114p2YN5+FuIXSfmfAVvOU5ur0VXhhGXM2Gh8Uz860AosRJIp8Zzg7jXNuOBKeFkugMStSfz6KYZYGw/p6qAp4MsFV43N0HpGt8hIQqEKeZfM0c1IHqDCnTczKTlnXgaAALLkKUWwyjaFJikSXSU7JyZwpi30qeJ6cA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: postgresql-secrets
      namespace: auth
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: authentik-secrets
  namespace: auth
spec:
  encryptedData:
    authentik-secret-key: AgAtALR6l2whHith/d0srb9mA3rhgQawYIi4rTxxtStYkldYFsE27i46UZ48uiaccTqbyQ4oyAFdCwKh0wqlimNmA1CcsqbJBgoWXauiP0zvaLfGQPqnSc6E+FNP6KM6iBtmstn4Ens7S/ThY0Qq6JxhPuyUReYTTO7A6xUxXAl17RdUGfHodMQso/pOHGR5vYbwBwXa1Hc6z2TROlDlGmTBBnk+Vupjo4eMVEFAqqCLE3GpjVWFZ5C+mjOIFSO3Bdm+nGQ5VnnX49kBKiLOe0AWYPDVymNT1onuBYMoN3VtP8BsALcUEflas5d/x5fscgQ1z6HVI4IFh8tFkT+v78+JVjBiki8GPPBa7W4A+sDpxQQI+Ubz56wqMyWj0we2yv+Mj+iudT1X44uITqe9bNnqC0g81zJ8xbygvxKhTwep8VDl+vcCFps64w/+AxtgaaDv4I9rVtgpIKxTvtAsNOk1u60DGkJ361rnCdyLfvAEYbnZ4Nzomo9a6VIEq8i7KlTcMbLD6090FsEzHerkZWrbsJB4N+LOgyBlbHpAIU/tMdIqe2K8af3k/3CXpaCpNPJfbQ7Lws7TrlLtZ0/BsnLh2oxH1epNAsYgH53B83F7nBvXXkyenCSj1NVs071Bl4oCVU4aPSuTMaAX9lqJAesypSRLW2BOTh2a01r1GATDwoyHI5XIDLq9Ap3TwYmq+/L0j9Uti17FNaqHBbCLDyE2y8DkxZQpq4hx+5HvXevmkpUDvvDxpeI8G4l+/IaZq4zxog==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: authentik-secrets
      namespace: auth
    type: Opaque
