authentik:
  secret_key: file:///authentik-secrets/authentik-secret-key
  postgresql:
    user: file:///postgresql-secrets/username
    password: file:///postgresql-secrets/password

global:
  envFrom:
  - secretRef:
      name: authentik-bootstrap-secrets

postgresql:
  enabled: true
  auth:
    existingSecret: postgresql-secrets

redis:
  enabled: true

server:
  volumes:
  - name: authentik-secrets
    secret:
      secretName: authentik-secrets
  - name: postgresql-secrets
    secret:
      secretName: postgresql-secrets
  volumeMounts:
  - name: authentik-secrets
    mountPath: /authentik-secrets
    readOnly: true
  - name: postgresql-secrets
    mountPath: /postgresql-secrets
    readOnly: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - authentik.${DOMAIN}

worker:
  volumes:
  - name: postgresql-secrets
    secret:
      secretName: postgresql-secrets
  volumeMounts:
  - name: postgresql-secrets
    mountPath: /postgresql-secrets
    readOnly: true
