authentik:
  secret_key: file:///authentik-creds/authentik-secret-key
  postgresql:
    host: postgres.${DOMAIN}
    user: file:///authentik-creds/authentik-postgres-username
    password: file:///authentik-creds/authentik-postgres-password
  redis:
    host: redis.${DOMAIN}

postgresql:
  enabled: true

redis:
  enabled: true

server:
  volumes:
  - name: authentik-creds
    secret:
      secretName: authentik-secrets
  volumeMounts:
  - name: authentik-creds
    mountPath: /authentik-creds
    readOnly: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - authentik.${DOMAIN}

worker:
  volumes:
  - name: authentik-creds
    secret:
      secretName: authentik-secrets
  volumeMounts:
  - name: authentik-creds
    mountPath: /authentik-creds
    readOnly: true
