authentik:
  secret_key: file:///authentik-secrets/authentik-secret-key
  bootstrap_token: file:///authentik-bootstrap-secrets/token
  bootstrap_password: file:///authentik-bootstrap-secrets/password
  postgresql:
    user: file:///postgresql-secrets/username
    password: file:///postgresql-secrets/password

postgresql:
  enabled: true
  auth:
    existingSecret: postgresql-secrets

redis:
  enabled: true

server:
  volumes:
  - name: authentik-secrets
    secret:
      secretName: authentik-secrets
  - name: authentik-bootstrap-secrets
    secret:
      secretName: authentik-bootstrap-secrets
  - name: postgresql-secrets
    secret:
      secretName: postgresql-secrets
  volumeMounts:
  - name: authentik-secrets
    mountPath: /authentik-secrets
    readOnly: true
  - name: authentik-bootstrap-secrets
    mountPath: /authentik-bootstrap-secrets
    readOnly: true
  - name: postgresql-secrets
    mountPath: /postgresql-secrets
    readOnly: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - authentik.${DOMAIN}

worker:
  volumes:
  - name: authentik-secrets
    secret:
      secretName: authentik-secrets
  - name: authentik-bootstrap-secrets
    secret:
      secretName: authentik-bootstrap-secrets
  - name: postgresql-secrets
    secret:
      secretName: postgresql-secrets
  volumeMounts:
  - name: authentik-secrets
    mountPath: /authentik-secrets
    readOnly: true
  - name: authentik-bootstrap-secrets
    mountPath: /authentik-bootstrap-secrets
    readOnly: true
  - name: postgresql-secrets
    mountPath: /postgresql-secrets
    readOnly: true
