#!/bin/bash

set -eu

dry_run_mode="none"

while getopts "d" flag; do
    case $flag in
    d)
        echo "Running dry-run mode..."
        dry_run_mode="server"
        ;;
    \?)
        echo "Wrong argument"
        exit 1
        ;;
    esac
done

project_path="$(git rev-parse --show-toplevel)"

# Common resources
echo -e "\nDeploying common resources..."
common_dir="${project_path}/common"

# Deploy namespace
kubectl apply -f "${common_dir}"/00-namespace.yaml
echo -e "Done!\n"

# lldap-bootstrap
echo -e "\nRunning lldap-bootstrap..."
lldap_bootstrap_dir="${project_path}/job/lldap-bootstrap"

kubectl apply -f "${lldap_bootstrap_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"

# Wait for lldap-bootstrap job to complete
if [[ "${dry_run_mode}" == "none" ]]; then
    echo -e "\nWaiting for lldap-bootstrap job to complete..."
    kubectl wait -n auth --for=condition=complete job/lldap-bootstrap --timeout=60s
else
    echo -e "\nSkipping waiting for lldap-bootstrap job in dry-run mode..."
fi

# lldap
echo -e "\nDeploying lldap..."
lldap_dir="${project_path}/lldap"

# Replace env variables
envsubst <"${lldap_dir}"/02-ingress-route.yaml | sponge "${lldap_dir}"/02-ingress-route.yaml

kubectl apply -f "${lldap_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"
